openapi: 3.1.0
info:
  title: API входа
  version: 0.0.1
servers:
  - url: /v0
paths:
  /admission/methods:
    get:
      summary: Список методов, доступных для входа
  /admission:
    post:
      summary: Начало процесса входа
    patch:
      summary: Передача необходимых реквизитов для шага процесса входа
