openapi: 3.1.0
info:
  title: API входа
  version: 0.0.1
servers:
  - url: /v0
definitions:
  Redirect:
    description: Редирект на переданный вами URI
  AdmissionType: string
  Provider:
    description: Имя провайдера социальной сети, к примеру gos-uslugi-oauth2
    type: string
  RedirectURI:
    description: URL на который произойдет редирект после успешной авторизации
    type: string
  FormName:
    description: Наименование формы, к примеру `signIn` или `signUp`
    type: string
  ApplicationId:
    description: ID вашего приложения
    type: string

  statuses:
    200:
      description: Успешный ответ
    429:
      description: Слишком много попыток
    404:
      description: Приложение с таким идентификатором не было найдено
components:
  schemas:
    Common:
      type: object
      required: application_id
      properties:
        application_id:
          $ref: "#/definitions/ApplicationId"
  parameters:
    Common:
      in: path
      name: application_id
      $ref: "#/definitions/ApplicationId"
      required: true
      type: string
paths:
  /admission/methods:
    get:
      summary: Получение способов авторизации
      description: Данный роут предназначен для получения всех возможных вам способов авторизации
      parameters:
        - $ref: "#/components/parameters/Common"
      required:
        - application_id
      responses:
        200:
          $ref: "#/definitions/statuses/200"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      description: Тип авторизации, который вы хотите использовать
                      type: string
        429:
          $ref: "#/definitions/statuses/429"
        404:
          $ref: "#/definitions/statuses/404"

  /admission:
    post:
      summary: Авторизация
      description: Optional description in *Markdown*
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/Common"
              oneOf:
                - type: object
                  title: Обычная
                  properties:
                    redirect_uri:
                      $ref: "#/definitions/RedirectURI"
                  required:
                    - redirect_uri
                - type: object
                  description: Используйте данный роут для аутентификации через какой либо провайдер социальной сети. Успешный запрос вернет статус 302 и произведет редирект к указанному в connection провайдеру.
                  title: C помощью провайдера
                  properties:
                    provider:
                      $ref: "#/definitions/Provider"
                    redirect_uri:
                      $ref: "#/definitions/RedirectURI"
                  required:
                    - provider
                    - redirect_uri
                - type: object
                  title: Ручная
                  description: Используйте данный способ авторизации в том случае, если есть необходимость внедрения авторизации в свое приложение, не используя при этом редиректы и открытие новых окон.
                  properties:
                    mode:
                      type: string,
                      description: Следует указать как `manual`
                    formName:
                      $ref: "#/definitions/FormName"
                    data:
                      type: object
                      description: "Данные для отправки"
                  required:
                    - data
                    - mode
                    - formName
      responses:
        200:
          description: "Будут установлены соответствующие HTTP cookies"
        429:
          $ref: "#/definitions/statuses/429"
        404:
          $ref: "#/definitions/statuses/404"
  /profile:
    get:
      summary: Профиль пользователя
      description: Данный роут вернет объект пользователя с замаскированными данными.
      parameters:
        - $ref: "#/components/parameters/Common"
      responses:
        200:
          $ref: "#/definitions/statuses/200"
        429:
          $ref: "#/definitions/statuses/429"
        404:
          $ref: "#/definitions/statuses/404"
  /logout:
    post:
      summary: Выход из аккаунта
      description: Данный роут удалит сессию пользователя
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Common"
      responses:
        200:
          $ref: "#/definitions/statuses/200"
        429:
          $ref: "#/definitions/statuses/429"
        404:
          $ref: "#/definitions/statuses/404"
